import React from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Footer from './components/Footer';
import HeaderTop from './components/HeaderTop';
import HeaderMin from './components/HeaderMin';
import { CartProvider } from './components/CartContext';
import { ToastProvider } from './components/Toast';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider> 
          <ToastProvider> 
            <HeaderTop />
            <HeaderMin />
            {children}
            <Footer />
          </ToastProvider>
        </CartProvider>
      </body>
    </html>
  );
}